name: PR Visual Tests Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches: [test]

jobs:
  comment:
    name: Create GitHub Comment
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Extract PR Number
        id: pr
        run: echo "::set-output name=id::$(<pr/pr-id.txt)"
        shell: bash
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_KEY_ID }}
          AWS_DEFAULT_REGION: ru-central1
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 cp playwright-report s3://diplodoc-playwright-reports/components/test-report/${{ steps.pr.outputs.id}}/ --endpoint-url=https://storage.yandexcloud.net  --recursive
        shell: bash
      - name: Create Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr.outputs.id }}
          header: visual tests report
          message: '[Visual Tests Report](https://storage.yandexcloud.net/diplodoc-playwright-reports/components/test-report/${{ steps.pr.outputs.id }}/index.html) is ready.'
