name: Update Component Screenshots

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/update-screenshots')

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright:v1.48.2-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Packages
        run: npm ci
      - name: Install Demo Packages
        run: cd demo && npm i
      - name: Build Files
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Update screenshots
        env:
            HOME: /root
        run: |
          npm run test:playwright:update

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update screenshots" && git push)

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: success()
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'âœ… Screenshots have been updated successfully!'
            });
